### ISSUE TITLE
Throws error when in use with skill-simple-youtube

### ISSUE THREAD

**Issue by Y0ngg4n** [OpenVoiceOS/skill-ovos-common-play#5]
```
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-ovos-common-play.openvoiceos/__init__.py", line 163, in handle_play_intent
    media_type = self.classify_media(utterance)
  File "/opt/mycroft/skills/skill-ovos-common-play.openvoiceos/__init__.py", line 93, in classify_media
    pred = self.media_intents.calc_intent(query)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/padacioso/__init__.py", line 75, in calc_intent
    default={'name': None, 'entities': {}}
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/padacioso/__init__.py", line 41, in calc_intents
    entities = simplematch.match(r, query, case_sensitive=True)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/simplematch.py", line 158, in match
    return Matcher(pattern, case_sensitive=case_sensitive).match(string)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/simplematch.py", line 80, in __init__
    self.regex = self._create_regex(pattern)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/simplematch.py", line 109, in regex
    self._regex_compiled = re.compile(value, flags=flags)
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 813, in _parse
    raise source.error(err.msg, len(name) + 1) from None
re.error: redefinition of group name 'query' as group 2; was group 1 at position 5
```

**Comment by Y0ngg4n** [comment]
@JarbasAl 
The query was "spiel rob zombie"

Skills.log:
```
2021-08-26 22:14:02.705 | INFO     |  4780 | mycroft.skills.skill_manager:_load_on_startup:275 | Skills all loaded!
2021-08-26 22:14:02.709 | INFO     |  4780 | mycroft.skills.skill_manager:_start_settings_update:194 | Start settings update
2021-08-26 22:14:02.710 | INFO     |  4780 | msm.mycroft_skills_manager | invalidating skills cache
2021-08-26 22:14:02.711 | INFO     |  4780 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-08-26 22:14:02.764 | INFO     |  4780 | mycroft.skills.intent_services.padatious_service:train:81 | Training... (single_thread=False)
2021-08-26 22:14:02.852 | INFO     |  4780 | __main__:on_ready:185 | Skills service is ready.
2021-08-26 22:14:03.503 | INFO     |  4780 | mycroft.skills.intent_services.padatious_service:train:83 | Training complete.
2021-08-26 22:14:04.628 | WARNING  |  4780 | msm.mycroft_skills_manager | No such default skill: mycroft-pandora
2021-08-26 22:14:06.834 | INFO     |  4780 | AutoVolume | Mic thresh: 336.1483 Low level: 114.02127999999999 High level: 311.46752000000004
2021-08-26 22:14:06.835 | INFO     |  4780 | AutoVolume | Setting volume to :75%
2021-08-26 22:14:08.410 | INFO     |  4780 | mycroft.skills.skill_manager:send:66 | New Settings meta to upload.
2021-08-26 22:14:11.828 | INFO     |  4780 | AutoVolume | Mic thresh: 242.485875 Low level: 114.02127999999999 High level: 311.46752000000004
2021-08-26 22:14:11.828 | INFO     |  4780 | AutoVolume | Setting volume to :60%
2021-08-26 22:14:27.700 | INFO     |  4780 | mycroft.skills.skill_manager:_start_settings_update:197 | All settings meta has been processed or upload has started
2021-08-26 22:14:28.270 | INFO     |  4780 | mycroft.skills.skill_manager:_start_settings_update:199 | Skill settings downloading has started
2021-08-26 22:14:31.057 | INFO     |  4780 | QuestionsAnswersSkill | Searching for spiele rob zombie
2021-08-26 22:14:32.043 | INFO     |  4780 | QuestionsAnswersSkill | Timeout occured check responses
2021-08-26 22:14:45.993 - OVOS - ovos_workshop.frameworks.playback.interface:stop:684 - DEBUG - Stopping playback
2021-08-26 22:14:47.432 - OVOS - ovos_workshop.skills.ovos:on_error:104 - ERROR - Bei der Verarbeitung der Anfrage ist ein Fehler im Skill Better Playback Control Skill aufgetreten.
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-ovos-common-play.openvoiceos/__init__.py", line 165, in handle_play_intent
    media_type = self.classify_media(utterance)
  File "/opt/mycroft/skills/skill-ovos-common-play.openvoiceos/__init__.py", line 95, in classify_media
    pred = self.media_intents.calc_intent(query)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/padacioso/__init__.py", line 75, in calc_intent
    default={'name': None, 'entities': {}}
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/padacioso/__init__.py", line 41, in calc_intents
    entities = simplematch.match(r, query, case_sensitive=True)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/simplematch.py", line 158, in match
    return Matcher(pattern, case_sensitive=case_sensitive).match(string)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/simplematch.py", line 80, in __init__
    self.regex = self._create_regex(pattern)
  File "/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/simplematch.py", line 109, in regex
    self._regex_compiled = re.compile(value, flags=flags)
  File "/usr/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 813, in _parse
    raise source.error(err.msg, len(name) + 1) from None
re.error: redefinition of group name 'query' as group 2; was group 1 at position 52
2021-08-26 22:14:57.180 | INFO     |  4780 | ConfigurationSkill | Remote configuration updated
```

**Comment by JarbasAl** [comment]
i think its behind the scenes intent, contains `{{query}}` twice

```
(spiel|spiele|beginn|beginne|start|starte) {{query}} (behind the scenes|behind scenes|behind the scene|hinter der bühne|hinter der szene|hinter der aufnahme) {{query}}
```

**Comment by Y0ngg4n** [comment]
@JarbasAl ah yeah seems legit.  i will change it tomorrow
